CREATE TABLE [dbo].[BAN] (
    [MABAN]     INT           NOT NULL,
    [TENBAN]    NVARCHAR (50) NULL,
    [TRANGTHAI] NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([MABAN] ASC)
);
go

CREATE TABLE [dbo].[THUCDON] (
    [MATHUCDON]  NVARCHAR (50) NOT NULL,
    [TENTHUCDON] NVARCHAR (50) NULL,
    [SOLUONG]    INT           NULL,
    [GHICHU]     NVARCHAR (50) NULL,
    [TENHINH]    NVARCHAR (50) NULL,
    [GIA]        FLOAT (53)    NULL,
    PRIMARY KEY CLUSTERED ([MATHUCDON] ASC)
);
go

CREATE TABLE [dbo].[TAIKHOAN] (
    [TENDN]   NVARCHAR (50) NOT NULL,
    [MATKHAU] NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([TENDN] ASC)
);
go

CREATE TABLE [dbo].[NHANVIEN] (
    [MANHANVIEN]  NVARCHAR (50) NOT NULL,
    [TENNHANVIEN] NVARCHAR (50) NULL,
    [DIENTHOAI]   NVARCHAR (50) NULL,
    [NGAYSINH]    DATETIME      NULL,
    [GIOITINH]    NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([MANHANVIEN] ASC)
);
go

CREATE TABLE [dbo].[GHICHU] (
    [MAGHICHU]  NVARCHAR (50) NOT NULL,
    [TENGHICHU] NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([MAGHICHU] ASC)
);
go

CREATE TABLE [dbo].[HOADON] (
    [MAHOADON]   INT        NOT NULL,
    [NGAYHOADON] DATETIME   NULL,
    [TRANGTHAI]  INT        NULL,
    [BAN]        INT        NULL,
    [TONGTIEN]   FLOAT (53) NULL,
    PRIMARY KEY CLUSTERED ([MAHOADON] ASC),
    CONSTRAINT [FK_HOADON_ToTable] FOREIGN KEY ([BAN]) REFERENCES [dbo].[BAN] ([MABAN])
);
go

CREATE TABLE [dbo].[CTHD] (
    [MACTHD]    INT           NOT NULL,
    [MAHD]      INT           NOT NULL,
    [MATHUCDON] NVARCHAR (50) NOT NULL,
    [SOLUONG]   INT           NULL,
    PRIMARY KEY CLUSTERED ([MACTHD] ASC),
    CONSTRAINT [FK_CTHD_ToTable] FOREIGN KEY ([MAHD]) REFERENCES [dbo].[HOADON] ([MAHOADON]),
    CONSTRAINT [FK_CTHD_ToTable_1] FOREIGN KEY ([MATHUCDON]) REFERENCES [dbo].[THUCDON] ([MATHUCDON])
);
go

Create proc USP_GetTableList
As Select * from dbo.BAN
Go